name: bottom_nav
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  custom_line_indicator_bottom_navbar: ^0.0.8
  day_night_switcher: ^0.2.0+1
  awesome_drawer_bar: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  contained_tab_bar_view: ^0.8.0
  carousel_slider: ^4.2.1
  clickable_list_wheel_view: ^0.2.0
  horizontal_data_table: ^4.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Images/cstlogo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Images/cstlogo.png
    - lib/Drawer/cstlogo.png
    - images/aboutLogo.jpeg
    - images/basketball_Login.jpeg
